application: aerial-ceremony-95901
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bower_components
  static_dir: bower_components

- url: /template
  static_dir: template

- url: /request/room_list
  script: handlers.app

- url: /request/room_detail
  script: handlers.app

- url: /test/data_update
  script: handlers.app

- url: /cron/data_update
  script: handlers.app

- url: /_ah/spi/.*
  script: library.api
  secure: always

libraries:
- name: endpoints
  version: latest

- name: lxml
  version: latest

- name: webapp2
  version: latest
